import {Vazirmatn} from "next/font/google";
import "./globals.css";

const vazir = Vazirmatn({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (<html lang="fa" dir={"rtl"}>
    <body className={`${vazir.className} bg-slate-950`}>
    {children}
    </body>
    </html>);
}
